name: Live Source Checker

on:
  schedule:
    - cron: "0 21 * * *"  # 每天美国时间 21:00 自动运行
  workflow_dispatch:

jobs:
  live-check:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行检测脚本
        run: |
          python optimized_live_checker.py
