name: Run Script and Push Changes

on:
  push:
    branches:
      - main  # 或者你自己指定的分支

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 设置Python环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 安装依赖
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests opencv-python

      # 运行Python脚本
      - name: Run Python script
        run: |
          python script.py

      # 创建文件路径并保存输出
      - name: Ensure output directory exists
        run: |
          mkdir -p assets/script
          touch assets/script/processed_index.txt
          touch assets/script/merged_output.txt

      # 提交并推送更改
      - name: Commit changes
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "your-email@example.com"
          git add .
          git commit -m "Update processed files and output"
          git push https://your_username:${{ secrets.GITHUB_TOKEN }}@github.com/your_username/your_repo.git HEAD:main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
