name: Sync Files to Cloudflare R2

on:
  # 定时触发：每天 23:50 UTC（美国东部时间 19:50，夏令时 UTC-4）
  schedule:
    - cron: '50 23 * * *'  # 这是 UTC 时间 23:50，等同于美国东部时间 19:50
  # 手动触发：你可以在 GitHub Actions 页面点击 "Run workflow" 来手动触发
  workflow_dispatch:   # 这个部分允许手动触发工作流

  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Sync live.txt to Cloudflare R2
      env:
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        export AWS_ENDPOINT="https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com"

        # 配置 AWS CLI 凭证
        aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
        aws configure set region "auto"
        aws configure set output json

        # 上传文件到 R2
        aws s3 cp ./live.txt s3://optimization/live.txt --endpoint-url "$AWS_ENDPOINT"
