name: Sync Live Sources to R2

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间零点触发一次（可根据需求调整）
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-to-r2:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Upload live sources to Cloudflare R2 without AWS CLI
      - name: Upload Live Sources to R2
        run: |
          # 确认文件路径和存储桶路径
          echo "当前路径：$(pwd)"
          echo "上传文件：./merged_output.txt"
          
          # 使用 curl 直接上传文件到 R2 存储桶
          curl -X PUT --data-binary @./merged_output.txt \
            -H "Content-Type: text/plain" \
            -H "x-amz-acl: public-read" \
            https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com/zhixue-tv/%E7%9F%A5%E9%9B%AA.txt

      # 可选步骤：如果需要，清除 Cloudflare 缓存
      - name: Invalidate Cloudflare Cache
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/zones/<your-zone-id>/purge_cache" \
          -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_KEY }}" \
          -H "Content-Type: application/json" \
          --data '{"purge_everything":true}'
