name: Sync Files to Cloudflare R2

on:
  schedule:
    - cron: '50 23 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

    - name: Sync live.txt to Cloudflare R2
      env:
        R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
        R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
        R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
      run: |
        # 配置 AWS CLI 的 R2 凭证和区域
        aws configure set aws_access_key_id "$R2_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$R2_SECRET_ACCESS_KEY"
        aws configure set region "auto"
        aws configure set output json
        
        # 设置 Cloudflare R2 的 S3 兼容端点 URL
        aws configure set s3.endpoint_url "https://f0f6bddeda81f13cec09327818e9348b.r2.cloudflarestorage.com"
        
        # 清除 AWS CLI 缓存（防止使用默认 AWS S3 端点）
        aws configure set cli_follow_urlparam false

        # 同步 live.txt 文件到 Cloudflare R2
        aws s3 cp ./live.txt s3://optimization/live.txt
